// ============================================================
// service-worker.js  —  AmmoniteID Service Worker
// Caches app shell + TFJS model shards for full offline use
// ============================================================
// Install:
//   navigator.serviceWorker.register('/static/service-worker.js')
// ============================================================

'use strict';

const SW_VERSION   = 'v4';
const CACHE_SHELL  = `ammonite-shell-${SW_VERSION}`;
const CACHE_MODEL  = `ammonite-model-${SW_VERSION}`;

// ── App shell: always cache these on install ──────────────
const SHELL_ASSETS = [
    '/static/home.html',
    '/static/test.html',
    '/static/mylog.html',
    '/static/upgrade.html',
    '/static/upgrade-success.html',
    '/static/login.html',
    '/static/my-account.html',
    '/static/admin.html',
    '/static/review.html',
    '/static/about.html',
    '/static/contact.html',
    '/static/partners.html',
    '/static/terms.html',
    '/static/privacy.html',
    '/static/disclaimer.html',
    '/static/tier-gates.js',
    '/static/hamburger-menu.js',
    '/static/responsive-mobile.css',
    '/static/auth-sync.js',
    '/static/feature-gate.js',
    '/static/offline-engine.js',
    '/static/class_info.json',
    'https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@4.20.0/dist/tf.min.js',
];

// ── Model assets: cache on first fetch, reuse thereafter ─
// (these are large — service worker caches them so IDB and
//  SW cache both work; whoever is first wins)
const MODEL_BASE   = '/static/tfjs_model/';
const MODEL_JSON   = MODEL_BASE + 'model.json';

// Shard filenames — must match what model.json weightsManifest lists.
// Using 5-shard naming convention generated by tensorflowjs_converter.
const SHARD_NAMES  = [
    'group1-shard1of5.bin',
    'group1-shard2of5.bin',
    'group1-shard3of5.bin',
    'group1-shard4of5.bin',
    'group1-shard5of5.bin',
];
const MODEL_ASSETS = [MODEL_JSON, ...SHARD_NAMES.map(s => MODEL_BASE + s)];

// ── Install: pre-cache shell ───────────────────────────────
self.addEventListener('install', (event) => {
    console.log('[SW] Installing', SW_VERSION);
    event.waitUntil(
        caches.open(CACHE_SHELL).then(async (cache) => {
            const results = await Promise.allSettled(
                SHELL_ASSETS.map(url =>
                    cache.add(url).catch(e =>
                        console.warn('[SW] Shell asset failed:', url, e.message)
                    )
                )
            );
            const ok  = results.filter(r => r.status === 'fulfilled').length;
            const bad = results.filter(r => r.status === 'rejected').length;
            console.log(`[SW] Shell cached: ${ok} ok, ${bad} failed`);
        })
    );
    self.skipWaiting();
});

// ── Activate: prune stale caches ──────────────────────────
self.addEventListener('activate', (event) => {
    console.log('[SW] Activating', SW_VERSION);
    event.waitUntil(
        caches.keys().then(keys =>
            Promise.all(
                keys
                    .filter(k => k !== CACHE_SHELL && k !== CACHE_MODEL)
                    .map(k => {
                        console.log('[SW] Deleting old cache:', k);
                        return caches.delete(k);
                    })
            )
        ).then(() => self.clients.claim())
    );
});

// ── Fetch: serve from cache, update in background ─────────
self.addEventListener('fetch', (event) => {
    const url = event.request.url;

    // Never intercept Firebase, API calls, or non-GET
    if (event.request.method !== 'GET')             return;
    if (url.includes('firebasejs'))                 return;
    if (url.includes('/api/'))                      return;
    if (url.includes('/identify'))                  return;
    if (url.includes('firebase'))                   return;
    if (url.includes('googleapis.com'))             return;

    // Model shards → cache-first (immutable large files)
    if (url.includes('/tfjs_model/')) {
        event.respondWith(cacheFirst(event.request, CACHE_MODEL));
        return;
    }

    // TFJS CDN → cache-first
    if (url.includes('jsdelivr.net') && url.includes('tfjs')) {
        event.respondWith(cacheFirst(event.request, CACHE_SHELL));
        return;
    }

    // class_info.json → stale-while-revalidate (may be updated server-side)
    if (url.includes('class_info.json')) {
        event.respondWith(staleWhileRevalidate(event.request, CACHE_SHELL));
        return;
    }

    // App shell (HTML + static JS) → stale-while-revalidate
    if (url.includes('/static/')) {
        event.respondWith(staleWhileRevalidate(event.request, CACHE_SHELL));
        return;
    }

    // Everything else → network with cache fallback
    event.respondWith(networkWithFallback(event.request, CACHE_SHELL));
});

// ── Cache strategies ───────────────────────────────────────

/** Return from cache immediately; if absent, fetch + cache. */
async function cacheFirst(request, cacheName) {
    const cache  = await caches.open(cacheName);
    const cached = await cache.match(request);
    if (cached) return cached;
    try {
        const response = await fetch(request.clone());
        if (response.ok) cache.put(request, response.clone());
        return response;
    } catch (e) {
        console.warn('[SW] cacheFirst network fail:', request.url);
        throw e;
    }
}

/** Return cached version immediately; refresh cache in background. */
async function staleWhileRevalidate(request, cacheName) {
    const cache  = await caches.open(cacheName);
    const cached = await cache.match(request);

    const fetchAndCache = fetch(request.clone())
        .then(response => {
            if (response.ok) cache.put(request, response.clone());
            return response;
        })
        .catch(() => null);

    return cached || await fetchAndCache || offlineFallback(request);
}

/** Try network; fall back to cache; fall back to offline page. */
async function networkWithFallback(request, cacheName) {
    try {
        const response = await fetch(request.clone());
        if (response.ok) {
            const cache = await caches.open(cacheName);
            cache.put(request, response.clone());
        }
        return response;
    } catch (_) {
        const cache  = await caches.open(cacheName);
        const cached = await cache.match(request);
        return cached || offlineFallback(request);
    }
}

/** Minimal offline fallback for HTML pages. */
function offlineFallback(request) {
    if (request.headers.get('accept')?.includes('text/html')) {
        return new Response(
            `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
<title>AmmoniteID — Offline</title>
<style>body{font-family:Arial,sans-serif;text-align:center;padding:4rem;background:#F5F1E8;}
h1{color:#2c5f2d;}p{color:#5D4E3A;font-size:1.1rem;}a{color:#2c5f2d;font-weight:bold;}</style>
</head><body>
<h1>🐚 AmmoniteID</h1>
<p>You're offline and this page isn't cached yet.</p>
<p><a href="/static/test.html">Go to Identify page</a> — available offline once visited.</p>
</body></html>`,
            { headers: { 'Content-Type': 'text/html' } }
        );
    }
    return new Response('Offline', { status: 503 });
}

// ── Message handler (manual cache control from page) ──────
self.addEventListener('message', async (event) => {
    const { type } = event.data || {};

    if (type === 'SKIP_WAITING') {
        self.skipWaiting();
        return;
    }

    if (type === 'CACHE_MODEL') {
        // Triggered by offline-engine after download — ensure SW also has model
        const cache = await caches.open(CACHE_MODEL);
        await Promise.allSettled(
            MODEL_ASSETS.map(url =>
                cache.match(url).then(hit => {
                    if (!hit) return fetch(url).then(r => r.ok && cache.put(url, r));
                })
            )
        );
        event.source?.postMessage({ type: 'MODEL_CACHED' });
        return;
    }

    if (type === 'GET_VERSION') {
        event.source?.postMessage({ type: 'VERSION', version: SW_VERSION });
        return;
    }

    if (type === 'CLEAR_MODEL_CACHE') {
        await caches.delete(CACHE_MODEL);
        event.source?.postMessage({ type: 'MODEL_CACHE_CLEARED' });
        return;
    }
});
